---
- name: configure_cephfs_backend | Get admin secret
  command: "ceph auth get-key client.admin"
  register: command_output_admin
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false

- name: configure_cephfs_backend | Set admin secret fact
  set_fact:
    cephfs_admin_secret: "{{ command_output_admin.stdout }}"

- name: configure_cephfs_backend | Ensure cephfs dir exists
  file:
    path: "{{ shared_storage_mountpoint }}/root"
    state: directory
    mode: 0755

- name: configure_cephfs_backend | Mount cephfs as admin user 
  mount:
    name: "{{ shared_storage_mountpoint }}/root"
    src: "{{ groups[mon_group_name][0] }}:/"
    fstype: "ceph"
    opts: "name=admin,secret={{ cephfs_admin_secret }},_netdev"
    state: mounted

- name: configure_cephfs_backend | Create directory for data
  file:
    path: "{{ shared_storage_mountpoint }}/root/fsgw"
    state: directory
    mode: 0755

- name: configure_cephfs_backend | Unmount cephfs as admin user 
  mount:
    name: "{{ shared_storage_mountpoint }}/root"
    state: absent 

- name: configure_cephfs_backend | Create samba cephx user
  ceph_key:
    name: "{{ item.name }}"
    state: present
    caps: "{{ item.caps }}"
    cluster: "{{ cluster }}"
    secret: "{{ item.key | default('') }}"
  with_items: "{{ samba_keyring }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: configure_cephfs_backend | Get samba secret
  command: "ceph auth get-key client.samba"
  register: command_output_samba
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false

- name: configure_cephfs_backend | Set samba secret fact
  set_fact:
    cephfs_samba_secret: "{{ command_output_samba.stdout }}"

- name: configure_cephfs_backend | write ceph samba client key 
  copy:
    content: "{{ cephfs_samba_secret }}"
    dest: /etc/ceph/samba.secret
    force: yes
    group: ceph
    owner: ceph
    mode: 0600

- name: configure_cephfs_backend | mount {{ shared_storage_mountpoint }}/fsgw
  mount:
    name: "{{ shared_storage_mountpoint }}/fsgw"
    src: "{{ groups[mon_group_name][0] }}:/fsgw"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,noatime"
    state: mounted